#!/bin/bash
[% c("var/set_default_env") -%]
output_dir=[% dest_dir %]/[% c('project') %]
gradle_repo=$rootdir/[% c('input_files_by_name/gradle-dependencies') %]
export GRADLE_MAVEN_REPO="file://$gradle_repo"

# The download script assumes the artifact package name is the complete URL path.
# In some cases this is incorrect, so copy those artifacts to the correct location
cp -r $gradle_repo/guardianproject/gpmaven/master/* $gradle_repo
cp -r $gradle_repo/dl/android/maven2/* $gradle_repo

mkdir -p /var/tmp/build $output_dir

[% pc(c('var/compiler'), 'var/setup', { compiler_tarfile => c('input_files_by_name/' _ c('var/compiler')) }) %]
tar -C /var/tmp/build -xf [% project %]-[% c('version') %].tar.gz

# Build Android Libraries
cd /var/tmp/build/[% project %]-[% c('version') %]
patch -p1 < $rootdir/transports.patch
$GRADLE_HOME/gradle-4.1/bin/gradle --offline build -x lint

# Package AAR files
for d in 'jsocksAndroid' 'APTDispatchLibrary' 'APTDispatchLibrary-MeekObfs4-Full'
	do cp ${d}/build/outputs/aar/* $output_dir
done
cp goptbundle/goptbundle.aar $output_dir
