#!/bin/bash
[% c("var/set_default_env") -%]
mkdir -p /var/tmp/build [% dest_dir _ '/' _ c('filename') %]

[% pc(c('var/compiler'), 'var/setup', { compiler_tarfile => c('input_files_by_name/' _ c('var/compiler')) }) %]
tar -C /var/tmp/build -xf [% project %]-[% c('version') %].tar.gz

cd /var/tmp/build/[% project %]-[% c('version') %]/orbotservice/src/main
/var/tmp/dist/android-toolchain/android-ndk/ndk-build
mv libs/armeabi/pdnsd libs/armeabi/pdnsd.so
mv libs/armeabi-v7a/pdnsd libs/armeabi-v7a/pdnsd.so
mv libs/x86/pdnsd libs/x86/pdnsd.so

cd /var/tmp/build/[% project %]-[% c('version') %]
./gradlew build -x lint

#TODO: package and sign debug
