#!/bin/bash
[% c("var/set_default_env") -%]
output_dir=[% dest_dir %]/[% c('filename') %]
gradle_repo=$rootdir/[% c('input_files_by_name/gradle-dependencies') %]
export GRADLE_MAVEN_REPO="file://$gradle_repo"
cp -r $gradle_repo/guardianproject/gpmaven/master/* $gradle_repo
cp -r $gradle_repo/dl/android/maven2/* $gradle_repo

mkdir -p /var/tmp/build $output_dir

[% pc(c('var/compiler'), 'var/setup', { compiler_tarfile => c('input_files_by_name/' _ c('var/compiler')) }) %]
tar -C /var/tmp/build -xf [% project %]-[% c('version') %].tar.gz

# Patch projects
cd /var/tmp/build/[% project %]-[% c('version') %]
patch -p1 < $rootdir/0001-Bug-28051-Build-Orbot-as-a-Library.patch
patch -p1 < $rootdir/set_gradle_repo_to_local.patch

# Build OrbotService Native Libraries
pushd /var/tmp/build/[% project %]-[% c('version') %]/orbotservice/src/main
/var/tmp/dist/android-toolchain/android-ndk/ndk-build
mv libs/armeabi/pdnsd libs/armeabi/pdnsd.so
mv libs/armeabi-v7a/pdnsd libs/armeabi-v7a/pdnsd.so
mv libs/x86/pdnsd libs/x86/pdnsd.so
popd

# Build Android Libraries and Apps
$GRADLE_HOME/gradle-4.1/bin/gradle --offline assembleRelease -x lint

# Package
cp app/build/outputs/aar/* $output_dir
cp orbotservice/build/outputs/aar/* $output_dir
cp jsocksAndroid/build/outputs/aar/* $output_dir
