#!/bin/bash
[% c("var/set_default_env") -%]
gradle_repo=$rootdir/[% c('input_files_by_name/gradle-dependencies') %]

# The download script assumes artifact package name is the complete URL path.
# In some cases this is incorrect, so copy those artifacts to correct location
cp -r $gradle_repo/dl/android/maven2/* $gradle_repo
cp -r $gradle_repo/maven2/* $gradle_repo
cp -r $gradle_repo/m2/* $gradle_repo

mkdir -p /var/tmp/build

[% pc(c('var/compiler'), 'var/setup', { compiler_tarfile => c('input_files_by_name/' _ c('var/compiler')) }) %]
tar -C /var/tmp/build -xf [% project %]-[% c('version') %].tar.gz

cd /var/tmp/build/[% project %]-[% c('version') %]
patch -p1 < $rootdir/buildconfig.patch
patch -p1 < $rootdir/buildsrc.patch
patch -p1 < $rootdir/enginegecko.patch
patch -p1 < $rootdir/geckodependency.patch
patch -p1 < $rootdir/git.patch
patch -p1 < $rootdir/gradlebuild.patch
patch -p1 < $rootdir/publish.patch
patch -p1 < $rootdir/settings.patch

mkdir -p /home/rbm/.m2/repository
cp -r $gradle_repo/* /home/rbm/.m2/repository
# Build Android Libraries and Apps
gradle --offline --no-daemon assemble -x lint
gradle publish

# Package
[% c('tar', {
        tar_src => [ "android-components" ],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
    }) %]
