#!/bin/bash
[% c("var/set_default_env") -%]
gradle_repo=$rootdir/[% c('input_files_by_name/gradle-dependencies') %]

# The download script assumes artifact package name is the complete URL path.
# In some cases this is incorrect, so copy those artifacts to correct location
cp -r $gradle_repo/dl/android/maven2/* $gradle_repo
cp -r $gradle_repo/maven2/* $gradle_repo
cp -r $gradle_repo/m2/* $gradle_repo
#cp -r $gradle_repo/artifactory/libs-release-bintray/* $gradle_repo

mkdir -p /var/tmp/build

[% pc(c('var/compiler'), 'var/setup', { compiler_tarfile => c('input_files_by_name/' _ c('var/compiler')) }) %]
tar -C /var/tmp/build -xf [% project %]-[% c('version') %].tar.gz

cd /var/tmp/build/[% project %]-[% c('version') %]
patch -p1 < $rootdir/git.patch
patch -p1 < $rootdir/maven-local.patch

# Build Android Libraries and Apps
gradle --offline --debug --no-daemon -Dmaven.repo.local=$gradle_repo assemble -x lint
gradle publishToMavenLocal

# Package
cd /home/rbm
[% c('tar', {
        tar_src => [ ".m2" ],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
    }) %]
