#!/bin/bash
[% c("var/set_default_env") -%]

export ANDROID_HOME=/var/tmp/dist/[% project %]
export PATH=$PATH:$ANDROID_HOME/tools/bin
export NDK_HOME=$ANDROID_HOME/NDK

#Make directories
mkdir -p $NDK_HOME $ANDROID_HOME

# Archives
unzip $HOME/sdk.zip -d $ANDROID_HOME
unzip $HOME/ndk.zip 

# Accept Android Licenses
/usr/bin/expect -c '
set timeout -1;
spawn '"${ANDROID_HOME}"'/tools/bin/sdkmanager --licenses;
  expect {
    "y/N" { exp_send "y\r" ; exp_continue }
    eof
  }
'

# Install Android packages
sdkmanager "platform-tools" "platforms;android-23" "build-tools;23.0.3" "build-tools;26.0.2" "extras;android;m2repository" "extras;google;m2repository"

# Archive dist directory
cd /var/tmp/dist
[% c('tar', {
        tar_src => [ project ],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
        }) %]

